server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           #payment_route #路由器的ID，没有固定规则单要求唯一，建议配置服务名
          #uri: http://localhost:8001  #静态路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #动态路由地址
          predicates:
            - Path=/payment/get/**      #断言 路径相匹配的进行路由

        - id: payment_routh2          #payment_route #路由的ID，没有固规则单要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:

            #1 After Route Predicate
            #- After=2020-04-13T11:27:55.882+08:00[Asia/Shanghai] #在这个时间以后才能正常访问

            #2 Before Route Predicate
            #- Before=2020-04-13T10:27:55.882+08:00[Asia/Shanghai] #在这个时间之前才能访问

            #3 Between Route Predicate 时间范围内可以访问
            #- Between=2020-04-13T10:27:55.882+08:00[Asia/Shanghai],2020-04-15T10:27:55.882+08:00[Asia/Shanghai]

            #4 Cooike Route Predicate 必须有cookie才能访问 第一个参数是cookie name，第二个是正则表达式
            #- Cookie=username, mrbean

            #5 Header Route Predicate 必须带有请求头信息，才能进入
            #- Header=X-Request-Id, \d+

            #6 Host Route Predicate
            #- Host=**.sxit.com

            #7 Method Route Predicate 只有指定类型方法，才能进入系统中
            - Method=GET #POST

            #8 Path Route Predicate 只有指定的路径才能访问
            - Path=/payment/lb/**       #断言，路径相匹配的进行路由

            #9 Query Route Predicate 要有参数username并且值是整数才能路由
            - Query=username, \d+


        - id: payment_routh3          #payment_route #路由的ID，没有固规则单要求唯一，建议配合服务名
          #uri: http://localhost:8001  #静态路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #动态路由地址
          predicates:
            - Path=/payment/create/**       #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka